# Generated by Django 5.1.7 on 2025-04-01 18:42

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/tmp'), upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cluster_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
